name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le déploiement sur les pushes vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./  # Le répertoire à publier, ici c'est la racine du projet
